### ISSUE TITLE
Try to maintain openness/compatibility with existing libraries

### ISSUE THREAD

**Issue by stappon** [opensourcebeehives/OSBH#3]
Adafruit unified sensor interface: https://github.com/adafruit/Adafruit_Sensor
Adafruit DHT: https://github.com/adafruit/DHT-sensor-library
Adafruit DHT unified: https://github.com/adafruit/Adafruit_DHT_Unified

These will not run on the spark core exactly as-is because they contain Arduino-specific includes. So we will have to fork them. However, the modifications required to make them work on the Spark core are very very minor.

I propose doing one of the following:
1) Fork these libraries into the OSBH github account as standalone repositories. Then add those forks as submodules (http://git-scm.com/book/en/v2/Git-Tools-Submodules) of this repository. This has the advantage of maintaining continuity and compatibility with the original libraries, in case we want to pull changes from them later, or submit pull requests.
2) Copy the source files of the libraries directly into subdirectories of this repository, as was done before. This has the advantage of simplicity.

My personal preference is for 1.

I also propose doing *both* of these things in the OSBH forks:
1) Preserving the original names of the classes
2) Keeping the original MIT licenses

**Comment by jacobron** [comment]
Looks like submodules can have some tricky steps we would have to come along (e.g. people downloading our repository would need to do more than just clone to get it working). Also every driver is in it's own repo, which means we would need to add more than one. As the Adafruit lib is anyways made for arduino we'll probably not merge our files with them.
I suggest going for simplicity and focus on our code, keeping the classes to be able to adapt to changes and suggest changes to the Adafruit drivers and Sensor libs "manually".

**Comment by stappon** [comment]
We are now using versions of the temperature and humidity libraries that more closely track the original Adafruit versions.
